/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stddef.h>


typedef union{

	volatile uint32_t whole;
	struct{
		uint32_t PIN0 :2;
		uint32_t PIN1 :2;
		uint32_t PIN2 :2;
		uint32_t PIN3 :2;
		uint32_t PIN4 :2;
		uint32_t PIN5 :2;
		uint32_t PIN6 :2;
		uint32_t PIN7 :2;
		uint32_t PIN8 :2;
		uint32_t PIN9 :2;
		uint32_t PIN10 :2;
		uint32_t PIN11 :2;
		uint32_t PIN12 :2;
		uint32_t PIN13 :2;
		uint32_t PIN14 :2;
		uint32_t PIN15 :2;
	}bits;

}MODER_t;

typedef struct{
	volatile MODER_t MODER;
	uint32_t volatile OTYPER;
	uint32_t volatile OSPEEDR;
	uint32_t volatile PUPDR;
	uint32_t volatile IDR;
	uint32_t volatile ODR;
	uint32_t volatile BSRR;
	uint32_t volatile LCKR;
}GPIO_Def;



typedef struct{
	uint32_t volatile RCC_CR;
	uint32_t volatile RCC_PLLCFGR;
	uint32_t volatile RCC_CFGR;
	uint32_t volatile RCC_CIR;
	uint32_t volatile RCC_AHB1RSTR;
	uint32_t volatile RCC_AHB2RSTR;
	uint32_t volatile RCC_AHB3RSTR;
	uint32_t volatile Reserved1;
	uint32_t volatile RCC_APB1RSTR;
	uint32_t volatile RCC_APB2RSTR;
	uint32_t volatile Reserved2;
	uint32_t volatile Reserved3;
	uint32_t volatile RCC_AHB1ENR;
	uint32_t volatile RCC_AHB2ENR;
	uint32_t volatile RCC_AHB3ENR;
	uint32_t volatile Reserved4;
	uint32_t volatile RCC_APB1ENR;

}RCC_Def;

#define GPIOA ((GPIO_Def*)0x40020000)
#define RCC ((RCC_Def*)0x40023800)


int main(void)
{
	volatile uint32_t s = sizeof(MODER_t);              // expect 4
	volatile uint32_t o = offsetof(GPIO_Def, OTYPER);

	RCC->RCC_AHB1ENR |= (1 << 0); // Set bit0 which is GPIOA clock enabled
//	GPIOA->MODER &= ~(3 << 10) ; // Set for Pin5 bit 10 ,11 to 00
//	GPIOA ->MODER |= (1 << 10); // Set for Pin5 bit 10 to 1
	GPIOA->MODER.bits.PIN5 = 1;
    /* Loop forever */
	for(;;){
		GPIOA->ODR ^= (1<<5);
		for(volatile int i =0; i<500000; i++);
	}
}
